### ISSUE TITLE
Picker not displayed

### ISSUE THREAD

**Issue by gomjota** [KasualBusiness/MaterialNumberPicker#1]
When I test the library with the same example that the author posts nothing happen:

MaterialNumberPicker numberPicker = new MaterialNumberPicker.Builder(this)
                        .minValue(1)
                        .maxValue(10)
                        .defaultValue(1)
                        .backgroundColor(Color.WHITE)
                        .separatorColor(Color.TRANSPARENT)
                        .textColor(Color.BLACK)
                        .enableFocusability(false)
                        .wrapSelectorWheel(true)
                        .build();

I am testing this with Android 6.0. Can anybody help me? Thank you.

**Comment by StephenVinouze** [comment]
This exemple as it states build a MaterialNumberPicker instance, but this is up to you how you display it. Typically you could show it inside a Dialog and let the user pick the value inside the MaterialNumberPicker then retrieve it when the user will validate from the Dialog callback. See the [sample](../tree/master/sample) project to know how to do it properly.
