### ISSUE TITLE
How to get the jar file?

### ISSUE THREAD

**Issue by AnandKhinvasara** [KasualBusiness/MaterialNumberPicker#2]
Gradle import and compilation is giving a lot of problems, please can you provide the jar file. Thanks

**Comment by StephenVinouze** [comment]
I just extended yesterday the README to let you configure your project using this library through Maven and by downloading the aar directly for non-Gradle users.

Note this is an .aar and not a .jar file in order to package Android resources files in it.

Please kindly let me know if you managed to get your project working.

**Comment by AnandKhinvasara** [comment]
Hi StephenVinouze, I am not using maven, I am using normal gradle given in Android Studio.

I added dependency in my gradle file as 
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'biz.kasual:materialnumberpicker:1.1.0'
}

As for as I know Gradle would pull the library from the artifact. But its not pulling for some reason. Is the artifact down?? Please help!

**Comment by StephenVinouze** [comment]
I just tried it on a dump project and it worked...

Can you give you the stack error?

Also do you have at least this configuration in your root `build.gradle` file :

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by AnandKhinvasara** [comment]
There is no stack error, it is building and compiling again. But when I try to import it in my files, its showing as empty

import biz.kasual.materialnumberpicker.MaterialNumberPicker; 

In the above import it says that cannot resolve 'MaterialNumberPicker'

**Comment by AnandKhinvasara** [comment]
And yes my build.gradle has the above code you mentioned

**Comment by AnandKhinvasara** [comment]
Hey I tried it on sample project and it worked their. There is something wrong in my project configuration it seems!!

**Comment by StephenVinouze** [comment]
I don't know what causes this error. Can you check if at least the dependency has been downloaded in your external dependencies panel? If it is present then there is some misconfiguration in your project unrelated to the library.

**Comment by StephenVinouze** [comment]
Ok then just let me know when you find what caused your problem so that I can clause this issue

**Comment by AnandKhinvasara** [comment]
I dont know the problem. Basically my android studio was not resolving any dependency at all for some reason. So its a very specific issue related to my system. I reinstalled android studio and its working now. Thanks for all the responses and help!
