### ISSUE TITLE
How to change font size of numbers?

### ISSUE THREAD

**Issue by AnandKhinvasara** [KasualBusiness/MaterialNumberPicker#3]
I mean suppose we have to pick from 0 - 10. The font size of the number is pretty small and I would like to increase the font size. 

Thanks,
Anand

**Comment by StephenVinouze** [comment]
I just released a newer version (1.1.1) that lets you change the text size. 

Please keep in mind that this library is basically using the native NumberPicker and such behavior was not intended. As such, you won't get your layout adjusted depending of the text size leading to cropped text. For instance if you choose a text size too big to be wrapped within the allocated height of each item inside the picker.

But considering what you needed, that should do the job :)

**Comment by AnandKhinvasara** [comment]
Thanks Stephen!!!

**Comment by crescent7272** [comment]
I have a problem with text size too. For Android 10 devices the text size supposed to be set 80sp otherwise it looks too small. But for lower apis it looks too big. It is really changing according to the api level. I need something that could work same for all apis. I  Thanks in advance.
