### ISSUE TITLE
separator shorter

### ISSUE THREAD

**Issue by Rainer-Lang** [KasualBusiness/MaterialNumberPicker#4]
Is it possible to show the separator a bit shorter?

**Comment by StephenVinouze** [comment]
I've looked into the native NumberPicker code and there is no easy way to do that using this library. As I stated in the README, it is exclusively based on the native picker and intends to let the access some basic properties using reflection.

The separator that is being used is a Drawable that is drawn by the component. I was able to color it but I cannot easily redraw its bounds. If you have an implementation idea you're welcome to propose it and pull request your code.

**Comment by Rainer-Lang** [comment]
Solved it.
I put one invisible button on the left and another on the right side of the MaterialNumberPicker and then used it with material-dialogs.
Therefore this is resolved for me.

Thanks for the lib and the styling options. :-)
