### ISSUE TITLE
Please also via xml

### ISSUE THREAD

**Issue by Rainer-Lang** [KasualBusiness/MaterialNumberPicker#5]
Really great lib!

**Comment by StephenVinouze** [comment]
Duplicate of #4

**Comment by Rainer-Lang** [comment]
Is it possible to use the extra styling and methods via xml? Would be helpful.

**Comment by StephenVinouze** [comment]
I could look into it. Should not be a problem ;)

**Comment by StephenVinouze** [comment]
I just released a newer version (1.2.0) that supports XML for each attributes. That should let you use this library any way you prefer (XML or programmatically) ;)

**Comment by Rainer-Lang** [comment]
@StephenVinouze Thanks a lot. I will try it.
Awesome! :-)
